assemble  original assemble inclusion}

diff --git a/s2i-scripts/.s2i/bin/assemble b/s2i-scripts/.s2i/bin/assemble
--- a/s2i-scripts/.s2i/bin/assemble
+++ b/s2i-scripts/.s2i/bin/assemble
@@ -1,1 +1,14 @@
-echo $(date '+%F %T') > /var/www/html/index.html
+#!/bin/bash
+echo "Making pre-invocation changes..."
+
+/usr/libexec/s2i/assemble
+rc=$?
+ if [ $rc -eq 0 ]; then
+   echo "Making post-invocation changes..."
+   echo $(date '+%F %T') > /var/www/html/date.html
+ else
+   echo "Error: assemble failed!"
+ fi
+
+exit $rc
+
